# Site settings
title: Lars Walen
email: lars@walen.me
description: >
  I'm a software engineer near Seattle who likes woodworking.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lars.walen.me" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

permalink: /:title
