#!/bin/bash

DIRECTORY=img

function files {
	find $DIRECTORY -mindepth 2 | egrep "^.*\.(png|jpg)" | grep -v _small
}

files | while read file
do
	small_file=$(echo "${file%.*}_small.${file##*.}")
	size=$(wc -c "$file" | cut -d ' ' -f 1)
	exif=$(identify -verbose "$file" | grep -i exif)

	if [ "$exif" ]
	then
		convert "$file" -strip "$file"
		echo "strip   :: $file"
	fi

	if [ -s "$small_file" ]
	then
		echo "exists  :: $small_file"
	elif [ "$size" -gt 10000 ]
	then
		convert "$file" -resize 512 "$small_file"
		echo "created :: $small_file"
	fi
done
